# Generated by Django 4.2 on 2025-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Profesor'), ('admin', 'Administrador')], default='student', help_text='Determina los permisos y accesos del usuario', max_length=10, verbose_name='Rol'),
        ),
    ]
