# Generated by Django 4.2 on 2025-04-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], default='estudiante', max_length=20),
        ),
    ]
