# Generated by Django 4.2 on 2025-04-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_asignatura_periodo_profesor_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='tipo_evaluacion',
            field=models.CharField(default='Final', max_length=50),
        ),
    ]
