# Generated by Django 4.2 on 2025-04-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_user_options_user_date_joined_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pregunta_seguridad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pregunta de recuperación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='respuesta_seguridad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Respuesta de recuperación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], default='estudiante', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
