name: Backend Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Backend (Django)
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ajusta la versión según tu entorno Django
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Migrations
        run: |
          python manage.py migrate  # Ejecuta las migraciones para tu base de datos
      - name: Collect Static Files
        run: |
          python manage.py collectstatic --noinput  # Recoge los archivos estáticos para que estén listos para ser servidos
      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: backacademico-gwatdzagd5g8dcbb  # Tu nombre de la aplicación web en Azure (backend)
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Este perfil lo obtienes desde Azure Portal
          package: '.'  # Ruta del código fuente de tu backend (en este caso es la raíz)
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/webapps-deploy@v2
        with:
          action: "close"
